shellcheck: SC2236: Use -n instead of ! -z.
Address the following warning:

```
ERROR: Found 1 shellcheck issue(s) which need to be resolved:
ERROR: ci/incluster_integration.sh:16:7: SC2236: Use -n instead of ! -z.
```